--all initial data is random from mockaroo
--tbl_users data
/*insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'bfallowfield0@ucoz.ru', 'ILHPHSYOqzL4');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ahowselee1@lulu.com', 'bpdt2UB62T');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'hcuddehay2@t.co', 'Cc7pxpTeGaEl');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ecurteis3@vimeo.com', 'rZqcFsxc4');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rweatherhogg4@weibo.com', 'IzOCrdD');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'eblankau5@hatena.ne.jp', 'sMmDpZpc442');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'kjelliman6@stanford.edu', 'f5IcvB');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cdefrancesco7@barnesandnoble.com', 'AfjZgMH');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jyu8@aboutads.info', 'v3vqXjCrQ');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'gtakis9@mlb.com', 'ZvL2kH');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mharmstonea@ifeng.com', 'ESxYbc');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'tcodab@hostgator.com', 'Mf3nxTs');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'obeechc@psu.edu', 'binhYG6u0hR');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'schaikovskid@w3.org', 'cabe4F');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jdougale@so-net.ne.jp', 'mw4Am9L');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'wacostaf@nhs.uk', 'qwFjh6Pm5M');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'aberringtong@flavors.me', 'yTnHGzaxH');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jrydingh@adobe.com', '5JhfFOa6lkYA');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dfentemi@shutterfly.com', 'oKMJaM');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'astapellsj@yelp.com', 'NNZqlTonAsav');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mbennetk@amazon.co.jp', 'c7Aq3nv9Fqle');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'achilcottel@bandcamp.com', 'jwKh0EkaRN');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rvelm@oracle.com', 'Lofqc48UDIaR');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mhalegarthn@e-recht24.de', 'nDe4zXSH');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'pchingo@theglobeandmail.com', 'cwznRBEd');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ebrogionip@qq.com', 'ceRXuEaR4');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'aswayneq@vinaora.com', 'j9PYZRo');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rfluckerr@list-manage.com', 'UCOKG5GVZ8DM');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dwinduss@jugem.jp', 'MiTsBJ6uL');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'wmakint@nature.com', 'NuhwAf');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'smeddemmenu@ox.ac.uk', 'QYNEDaK6vEcJ');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'fdaulbyv@networksolutions.com', '3xdWLndYjnD');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'lshrimptonw@artisteer.com', 'JgPmPKvWaNmV');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mpearlex@google.ru', 'DLZ2tcV');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'tblazey@gravatar.com', 'janJn31o');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rhatrickz@businessinsider.com', 'eAgTAZ9HJbTQ');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cshurmer10@nps.gov', 'YLcfkb');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'aronchka11@uiuc.edu', 'EutfH2TMXhp');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'croumier12@tmall.com', 'mKXLrjfv');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'brottenbury13@barnesandnoble.com', '3SoUF5C');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mspurgin14@cisco.com', 'aWTwx9Rzlo');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rbegin15@barnesandnoble.com', '0mxYwfyIa4');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'kbrient16@cocolog-nifty.com', '9BiBAk08');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'tdominique17@ebay.co.uk', 'deaBtf');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dbutterworth18@icq.com', 'E2KoYO');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cdoxey19@gizmodo.com', 'nOGaILs1Uu');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'agason1a@about.com', 'XiCzESCZa');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'emathie1b@123-reg.co.uk', '8QFrWf');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'drouff1c@shinystat.com', 'Cyp8zRh');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jmulliner1d@soup.io', 'fhjDE9Jnevhe');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'abeadell1e@ow.ly', 'HI7hPUeJq');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ebackler1f@hao123.com', 'TeZC87Lh');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rgwin1g@wunderground.com', 's7fcNhJV4ok');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'pgoulding1h@scribd.com', 'Oygffckpg');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'kbresson1i@google.com.au', 'vpbdYfh4iNH');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mroddell1j@senate.gov', 'nUz59M');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ldresser1k@jimdo.com', 'dZ6CkN');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'arapps1l@drupal.org', 'vlAbt2D');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jmcphilemy1m@sogou.com', 'CeHlmAhlOwvH');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cbenduhn1n@unblog.fr', 'LLZ6coS');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'gshiels1o@nytimes.com', 'ZAe0bIHNl');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'spalke1p@youtube.com', 'ZrRYtKzweCrJ');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'hdebenedictis1q@sfgate.com', 'oGwvKdXQrpgr');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mfrays1r@jigsy.com', 'yjmArHS');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mtomkinson1s@twitter.com', 'AgEhQl');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mkilmister1t@mysql.com', 'y0anExHdw');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rlockhart1u@fc2.com', 'I31hfU1kJs');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'sdumphries1v@wp.com', 'PnsIzWbK0B');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'tdadge1w@newsvine.com', 'RebXtbmAMGL');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mgeraldez1x@wordpress.com', '64nBS0');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dshory1y@cbsnews.com', '00C1Wvu');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'aroper1z@oracle.com', 'eIUb9v');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'anaismith20@microsoft.com', '2hj9KsYn');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'deustace21@nationalgeographic.com', 'Cl6jCK0');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'achander22@blogger.com', 'e6YQj7');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'edodson23@homestead.com', 'aI61eKhh');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'abarr24@yellowpages.com', 'Nqf3rJam');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'gstive25@theatlantic.com', 'eFYUSRKEt');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ajone26@aboutads.info', '8A8aO9c');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'efollin27@chicagotribune.com', 'jew8kkka');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jpiechnik28@usnews.com', '6CxlKGIZroe');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'rgaskill29@adobe.com', 'aKU1TR1ibR');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jmacadie2a@skype.com', 'MI7ysbATmC');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mbiever2b@slate.com', 'fZbCpMAV4Ti');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'imacgauhy2c@twitter.com', 'x9sNgScr8dIq');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'owycliff2d@yelp.com', 'V4iGOIk4');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'ndargie2e@fastcompany.com', 'z4G4j0AZ');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'tstaniforth2f@google.it', 'bdqr4ZnP');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cgarrood2g@cloudflare.com', 'jEgVkdHK');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cstquentin2h@live.com', 'W9g0YTJXRa4B');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'vjakubovski2i@blog.com', 'Iqx7sJOMJ1P5');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dkillingworth2j@adobe.com', 'yxRzHICA');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'cpidduck2k@google.pl', '5tMjucUOoRJz');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'srannigan2l@cbc.ca', 'DwV90vg9');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dtuminini2m@theguardian.com', '2PNq17');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'jpoulett2n@pbs.org', '6rYo9UVOirL1');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'mberisford2o@tinypic.com', 'bjzXBFIj6');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'dmartland2p@tripod.com', 'FC2IYwcr');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'yroostan2q@mac.com', 'rTrnf2E8');
insert into tbl_users (userID, userEmail, userPassword, userFName, userMInit, UserLName) values (default, 'kahern2r@washington.edu', 'tpoHAqgF');

update tbl_users set userFName = 'John', userMinit = 'A', userLName = 'Doe'
update tbl_users set useremail = 'barry912@revature.net', userPassword = 'P@5Sw0RD', userFName = 'Barry', userMInit = 'M', userLName = 'Norton' where userid = 208

--tbl_accounts data
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Face to face executive strategy', 1903.71, 239);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Cross-group dedicated core', 3397.81, 257);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Exclusive real-time open architecture', 7486.0, 306);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'User-centric 5th generation solution', 3603.83, 260);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Object-based zero defect installation', 8548.74, 304);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Organic didactic Graphical User Interface', 4298.68, 297);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Customer-focused directional hierarchy', 7780.53, 296);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Versatile incremental website', 6646.48, 224);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Persistent responsive emulation', 8528.31, 300);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Face to face dedicated implementation', 8927.41, 287);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Vision-oriented next generation focus group', 9711.09, 290);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Networked didactic ability', 273.54, 235);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Diverse real-time application', 2051.4, 218);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Pre-emptive systematic matrix', 6144.97, 253);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Programmable client-driven ability', 6716.05, 297);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'De-engineered next generation open system', 3541.99, 229);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Enterprise-wide systemic benchmark', 9854.25, 213);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Distributed intermediate standardization', 8815.57, 275);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Multi-tiered grid-enabled neural-net', 1062.85, 218);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Profound client-server leverage', 8122.98, 307);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Seamless didactic installation', 7475.48, 245);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Mandatory empowering secured line', 7536.48, 230);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Cloned incremental complexity', 3121.88, 269);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Multi-tiered tangible knowledge user', 4286.76, 265);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Future-proofed analyzing task-force', 9985.49, 287);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Assimilated motivating application', 8971.63, 259);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Digitized radical artificial intelligence', 3837.44, 260);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Advanced bandwidth-monitored software', 5305.01, 244);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Right-sized analyzing pricing structure', 1300.13, 236);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Face to face 24/7 frame', 3963.4, 250);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Centralized client-server intranet', 1293.22, 240);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Switchable attitude-oriented throughput', 6820.64, 290);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Open-architected zero tolerance instruction set', 6923.55, 212);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Implemented stable standardization', 8809.43, 224);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Multi-layered multi-tasking contingency', 1904.27, 263);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Reduced static challenge', 6231.38, 272);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Customer-focused cohesive structure', 6504.9, 302);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Versatile static website', 6173.42, 273);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Optimized transitional contingency', 5785.92, 265);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Centralized needs-based installation', 5946.27, 230);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Cross-platform zero administration utilisation', 2588.29, 286);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Customizable 3rd generation functionalities', 4678.21, 290);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Object-based background contingency', 113.9, 229);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Enterprise-wide 4th generation standardization', 8524.44, 241);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'User-centric tertiary open system', 3252.21, 244);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Visionary hybrid throughput', 5391.94, 235);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Digitized hybrid superstructure', 4921.58, 209);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Decentralized real-time open system', 1499.63, 252);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Cross-group eco-centric moderator', 8837.26, 240);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Monitored mission-critical alliance', 6633.14, 259);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Enterprise-wide next generation portal', 3088.92, 283);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Profound demand-driven monitoring', 9375.68, 244);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Adaptive maximized Graphic Interface', 8024.05, 222);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Persistent composite conglomeration', 4500.96, 234);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Programmable empowering knowledge base', 8970.92, 299);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Persistent dedicated model', 9597.27, 282);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Enhanced homogeneous website', 1037.1, 289);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Configurable well-modulated moderator', 3036.78, 224);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Programmable user-facing productivity', 4547.53, 238);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Diverse stable extranet', 267.96, 221);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Integrated high-level internet solution', 2030.38, 222);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Business-focused directional infrastructure', 4367.43, 226);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Universal didactic database', 549.53, 245);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Team-oriented local throughput', 6990.34, 217);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Vision-oriented optimal hub', 3710.8, 231);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Diverse analyzing paradigm', 210.41, 289);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Seamless client-driven structure', 9786.85, 293);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Total full-range protocol', 727.75, 214);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Phased high-level core', 577.08, 214);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Customer-focused systematic firmware', 6345.37, 236);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Cross-group grid-enabled open system', 2672.29, 286);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Stand-alone neutral customer loyalty', 3269.36, 260);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Optional needs-based task-force', 5854.16, 239);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Ergonomic holistic extranet', 5162.86, 307);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Reactive fresh-thinking capacity', 4226.17, 236);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Profound 24/7 instruction set', 4434.7, 303);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Organized zero defect data-warehouse', 8106.18, 275);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Devolved analyzing encryption', 8787.35, 256);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Re-engineered human-resource flexibility', 9528.02, 283);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Cross-platform 24 hour info-mediaries', 9469.68, 274);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Persevering high-level contingency', 5305.25, 260);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Right-sized explicit flexibility', 7026.85, 295);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Sharable bi-directional time-frame', 7240.56, 274);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Networked optimal artificial intelligence', 9868.19, 222);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Multi-channelled web-enabled concept', 4233.96, 291);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Ergonomic value-added matrix', 9805.33, 266);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'De-engineered static toolset', 6846.16, 231);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Profound zero defect focus group', 6609.17, 249);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Synchronised responsive algorithm', 879.55, 251);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Organized asynchronous flexibility', 6441.03, 254);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Implemented systematic standardization', 1244.77, 275);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Re-contextualized tangible support', 2080.93, 267);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Versatile high-level success', 9420.35, 280);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Front-line scalable local area network', 5435.88, 232);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Extended cohesive pricing structure', 5693.19, 211);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Joint', 'Re-contextualized dynamic adapter', 1118.52, 210);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Secured grid-enabled conglomeration', 562.24, 270);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Savings', 'Realigned multimedia strategy', 6274.5, 280);
insert into tbl_accounts (accountType, accountNotes, accountBalance, userID) values ('Checking', 'Balanced clear-thinking open system', 2025.6, 286);

update tbl_accounts set userid = 208 where userid = 222;
update tbl_accounts set accountnotes = 'test account' where userid = 208;
update tbl_accounts set accounttype = 'Joint' where accountid = 185;

--tbl_transactions data
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1159.22, 1903.71, 'Quality-focused local initiative', 102);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6703.54, 9140.82, 'Quality-focused directional leverage', 155);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 162.29, 8840.77, 'Reverse-engineered 6th generation ability', 135);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5044.54, 3843.9, 'Horizontal background structure', 125);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9951.19, 2833.33, 'Distributed reciprocal open system', 187);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7000.7, 7226.97, 'Enhanced hybrid knowledge user', 131);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2135.58, 8146.76, 'Object-based dedicated collaboration', 192);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4261.05, 1903.44, 'Digitized multi-state extranet', 191);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7928.18, 1471.97, 'Managed next generation support', 195);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7646.72, 1072.99, 'Programmable dynamic access', 109);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1199.69, 7337.44, 'Switchable executive task-force', 153);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3664.11, 2038.72, 'Object-based 5th generation structure', 146);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8986.12, 1225.94, 'Total asynchronous migration', 147);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5970.97, 4271.88, 'Diverse holistic hierarchy', 192);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4576.82, 1732.0, 'Object-based coherent framework', 141);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1093.28, 8698.2, 'Integrated regional neural-net', 176);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5766.87, 480.1, 'Innovative motivating complexity', 132);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4246.38, 552.66, 'Function-based methodical access', 133);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9046.39, 1182.7, 'Compatible analyzing algorithm', 105);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9256.14, 826.93, 'Enterprise-wide interactive pricing structure', 123);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2844.3, 2056.59, 'Multi-tiered next generation data-warehouse', 136);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7411.1, 3906.54, 'Ameliorated responsive portal', 137);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5869.79, 4121.43, 'Switchable tangible software', 136);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8893.69, 9875.7, 'Upgradable systematic architecture', 172);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9842.24, 9345.49, 'Profit-focused full-range analyzer', 175);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4794.01, 1903.71, 'Multi-channelled heuristic intranet', 102);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7036.46, 9600.6, 'Compatible 6th generation Graphical User Interface', 134);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2138.04, 4293.18, 'Compatible optimizing ability', 105);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8428.3, 5018.68, 'Exclusive dedicated structure', 125);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7738.9, 6215.47, 'Adaptive incremental hardware', 175);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 23.21, 7921.22, 'Versatile zero tolerance model', 179);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5299.22, 1123.82, 'Intuitive solution-oriented service-desk', 111);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3932.02, 4109.84, 'Customer-focused modular knowledge user', 105);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2829.08, 8824.78, 'Synergistic global open architecture', 193);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1270.34, 7919.33, 'Cross-group fault-tolerant structure', 175);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4211.41, 2198.69, 'Robust attitude-oriented customer loyalty', 151);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4265.29, 4775.43, 'Phased 24/7 complexity', 177);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8130.64, 7026.22, 'Robust bottom-line access', 176);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 272.53, 4566.11, 'Vision-oriented executive artificial intelligence', 115);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1318.58, 8953.79, 'Re-engineered interactive capacity', 126);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6474.9, 1255.02, 'Universal asynchronous product', 172);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4413.01, 6702.89, 'Implemented directional implementation', 178);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3668.06, 2239.73, 'Switchable exuding customer loyalty', 168);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2101.6, 1211.06, 'Universal national initiative', 132);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9108.0, 2888.01, 'Team-oriented 6th generation flexibility', 159);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1826.76, 5751.23, 'Balanced uniform software', 113);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1302.91, 4280.83, 'Face to face full-range open system', 108);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1449.34, 9623.3, 'Organized incremental challenge', 196);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2715.55, 4510.5, 'Horizontal 5th generation complexity', 157);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4055.07, 809.88, 'Mandatory multi-state moratorium', 144);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3299.12, 547.03, 'De-engineered attitude-oriented help-desk', 200);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2146.99, 113.83, 'Focused leading edge throughput', 110);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3484.45, 8487.62, 'Customer-focused logistical methodology', 123);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6759.21, 1701.0, 'Automated fault-tolerant analyzer', 112);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9397.98, 9195.33, 'Extended tertiary service-desk', 186);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7818.61, 465.42, 'Sharable composite strategy', 143);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7811.51, 9656.28, 'Object-based cohesive analyzer', 192);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5748.68, 3984.99, 'Distributed fault-tolerant data-warehouse', 111);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8421.72, 308.62, 'Decentralized responsive access', 109);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9517.62, 224.01, 'Monitored next generation knowledge base', 128);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4722.45, 7839.98, 'De-engineered tangible adapter', 162);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1166.41, 9023.64, 'User-friendly non-volatile definition', 190);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5268.11, 2928.92, 'Re-contextualized full-range projection', 163);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1253.68, 4416.35, 'Upgradable mobile installation', 107);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3.8, 3008.0, 'Universal grid-enabled superstructure', 177);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 496.86, 9552.35, 'Integrated responsive budgetary management', 125);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2205.15, 8336.24, 'Enterprise-wide holistic moderator', 190);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1986.77, 1670.3, 'Cross-platform zero tolerance process improvement', 144);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2298.39, 7320.84, 'Exclusive tangible core', 176);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5868.26, 5971.12, 'Re-engineered well-modulated project', 189);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4683.46, 1559.16, 'Re-contextualized composite infrastructure', 138);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 1170.37, 2443.74, 'Grass-roots contextually-based solution', 150);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5012.33, 385.37, 'Future-proofed 24/7 local area network', 194);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 5540.67, 3484.77, 'Operative human-resource challenge', 146);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 126.45, 1477.91, 'Triple-buffered methodical orchestration', 162);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7798.03, 2818.78, 'Adaptive optimizing artificial intelligence', 126);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4354.42, 6879.06, 'Monitored attitude-oriented installation', 106);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3447.98, 5295.83, 'Fully-configurable solution-oriented open architecture', 123);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6765.13, 7056.19, 'Multi-lateral mission-critical benchmark', 160);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4800.14, 1464.78, 'Universal client-server software', 195);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6835.27, 6353.22, 'Advanced dynamic project', 199);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2640.33, 6928.99, 'Optimized holistic website', 137);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 333.08, 2058.54, 'Monitored motivating support', 166);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2469.06, 6716.62, 'Reverse-engineered mission-critical infrastructure', 147);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6732.97, 8848.15, 'Operative regional artificial intelligence', 118);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7243.93, 3064.46, 'Polarised full-range matrix', 144);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 9123.79, 7731.33, 'Expanded tertiary definition', 168);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 942.55, 9360.33, 'Synergistic intangible support', 156);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6535.92, 7938.44, 'Quality-focused 5th generation task-force', 114);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8160.07, 180.3, 'Digitized static moratorium', 191);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 8922.46, 176.89, 'Centralized contextually-based encoding', 109);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 7546.6, 7200.16, 'Automated web-enabled software', 152);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 6834.05, 6155.67, 'Streamlined attitude-oriented architecture', 120);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 2123.01, 8461.68, 'Multi-layered national algorithm', 136);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 922.12, 7416.21, 'Robust systemic contingency', 106);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4015.17, 1405.7, 'Robust interactive extranet', 183);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4376.73, 3015.04, 'Decentralized object-oriented secured line', 159);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4171.25, 164.2, 'Business-focused cohesive utilisation', 182);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 3712.43, 5671.22, 'Innovative grid-enabled array', 140);
insert into tbl_transactions (transType, transPreBalance, transPostBalance, transNotes, accountID) values (null, 4762.76, 6444.65, 'Quality-focused motivating algorithm', 178);

update tbl_transactions t set transpostbalance = (select accountbalance from tbl_accounts a where a.accountid = t.accountid);
update tbl_transactions t set transtype = 'Withdraw' where transpostbalance < transprebalance;
update tbl_transactions t set transtype = 'Deposit' where transpostbalance > transprebalance;
update tbl_transactions set transdate = '1969-04-20';*/